"""SETU — Repayment Plans page."""

import streamlit as st

import portfolio_data as pf
import theme as th
import ui_components as ui


def render(records: list[dict]):
    clicked = ui.render_page_header(
        "Repayment Plans", "Dynamic schedules generated by SETU, pending officer approval or already in force.",
        actions=["Create plan"],
    )
    if clicked:
        st.toast('"Create plan" is a prototype action — plans are generated automatically from classification.')

    plans = pf.plan_register(records)
    active = sum(1 for p in plans if p["status"] == "Active")
    withheld = sum(1 for p in plans if p["status"] == "Withheld")
    deferred_total = sum(p["deferred"] for p in plans)
    months, fixed_med, dynamic_med = pf.fixed_vs_dynamic_dscr(records)
    uplift_pp = (dynamic_med[0] - fixed_med[0]) * 100 if fixed_med and dynamic_med else 0.0

    ui.render_kpi_row([
        {"label": "Active Plans", "value": f"{active}",
         "caption": f"{100*active/max(len(plans),1):.1f}% of book", "color": "blue"},
        {"label": "Human Review", "value": f"{withheld}",
         "caption": "Withheld — structural deterioration", "color": "red"},
        {"label": "Deferred Balance", "value": th.format_rupees(deferred_total),
         "caption": "Tracked, recoverable within tenure via peak-month top-ups", "color": "gray"},
        {"label": "DSCR Uplift", "value": f"{'+' if uplift_pp >= 0 else ''}{uplift_pp:.1f}pp",
         "caption": "Median next-month DSCR, dynamic vs fixed", "color": "green"},
    ])

    st.write("")
    st.markdown('<div class="setu-card">', unsafe_allow_html=True)
    ui.render_section_title("Plan register", "Every borrower with a SETU-adjusted schedule this cycle")
    header = st.columns([1.9, 1.1, 1.1, 1.1, 1.0, 1.1, 1.1])
    for c, label in zip(header, ["Borrower", "Plan", "Contract EMI", "Adjusted EMI", "Relief Used",
                                  "Deferred", "Status"]):
        c.markdown(f'<div class="setu-row-header" style="border-bottom:none;">{label}</div>',
                    unsafe_allow_html=True)
    st.markdown('<hr style="margin:0 0 0.4rem 0;">', unsafe_allow_html=True)
    for p in plans:
        cols = st.columns([1.9, 1.1, 1.1, 1.1, 1.0, 1.1, 1.1])
        cols[0].markdown(f'<div class="setu-name">{p["name"]}</div>'
                          f'<div class="setu-subtext">{p["borrower_id"]} · {p["borrower_type"]}</div>',
                          unsafe_allow_html=True)
        plan_cell = f'<span class="setu-link">{p["plan"]}</span>'
        if p["status"] == "Officer Review":
            plan_cell += (f'<div class="setu-small-muted">Ballpark {th.format_rupees(p["bridge_loan_low"])}'
                          f'–{th.format_rupees(p["bridge_loan_high"])}, pending review</div>')
        cols[1].markdown(plan_cell, unsafe_allow_html=True)
        cols[2].markdown(f'<div class="setu-value">{th.format_rupees(p["contract_emi"])}</div>',
                          unsafe_allow_html=True)
        cols[3].markdown(f'<div class="setu-value">{th.format_rupees(p["adjusted_emi"])}</div>',
                          unsafe_allow_html=True)
        cols[4].markdown(f'<div class="setu-value">{p["relief_used"]} / 2</div>', unsafe_allow_html=True)
        cols[5].markdown(f'<div class="setu-value">{th.format_rupees(p["deferred"])}</div>',
                          unsafe_allow_html=True)
        cols[6].markdown(ui.plan_status_badge_html(p["status"]), unsafe_allow_html=True)
        st.markdown('<hr style="margin:0.2rem 0;border-color:#eef0f2;">', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    st.write("")
    st.markdown('<div class="setu-card">', unsafe_allow_html=True)
    ui.render_section_title("Fixed vs. dynamic, portfolio view", "Median projected DSCR across the next 6 months")
    fig, ax = ui.new_fig((9, 3.0))
    ax.plot(months, fixed_med, color=th.TEXT_MUTED, linewidth=2.0, label="Traditional fixed")
    ax.plot(months, dynamic_med, color=th.SEMANTIC["blue"]["bar"], linewidth=2.2, label="SETU dynamic")
    ax.axhline(1.0, color=th.SEMANTIC["red"]["bar"], linewidth=1.0, linestyle=":")
    ax.text(0, 1.02, "DSCR 1.00", fontsize=7.5, color=th.SEMANTIC["red"]["fg"])
    ax.legend(loc="upper right", fontsize=8.5, frameon=False)
    ui.style_axes(ax)
    st.pyplot(fig, width="stretch")
    st.markdown('</div>', unsafe_allow_html=True)
